### PR TITLE
Backport 1.10.1 to Bionic

### PR DESCRIPTION
**Pull request by dramaturg**
This backports 1.10.1 to bionic.
No changes had to be made specific for bionic.

### CODE REVIEW

**Comment by dramaturg** [comment]
I checked puppet and we don't explicitly set the version of unbound so run the risk of breaking every single host if this builds a package that doesn't work with our config.
So I'll make a puppet PR first to `ensure` the current package so we can test and deploy this in a controlled manner.

**Comment by irregulator** [comment]
@dramaturg fwiw based on `pkg-unbound` job configuration as well as the respective [buildBackportsPackages](https://github.com/exoscale/jenkins-pipeline/blob/master/vars/buildBackportsPackages.groovy) used underneath, built packages will be only uploaded to staging not production. 

Additionally, I think Puppet only ensures a package is [installed](https://github.com/exoscale/puppet-unbound/blob/master/manifests/init.pp#L87), does not ensure latest version.

So all in all, I think we shall be okay even for staging.

**Comment by dramaturg** [comment]
> @dramaturg fwiw based on `pkg-unbound` job configuration as well as the respective [buildBackportsPackages](https://github.com/exoscale/jenkins-pipeline/blob/master/vars/buildBackportsPackages.groovy) used underneath, built packages will be only uploaded to staging not production.

Ah I didn't look into that yet. Still as the version jump is quite significant, I'd like to take baby steps and test the generated packages on a few single staging machines before going wild.


> Additionally, I think Puppet only ensures a package is [installed](https://github.com/exoscale/puppet-unbound/blob/master/manifests/init.pp#L87), does not ensure latest version.

We actually set `latest` in [common.yaml](https://github.com/exoscale/puppet/blob/6d506e1376a63b049205409bc5d18da9d38ce950/configstore/common.yaml#L33).
So I made a PR against Puppet to ensure we take it more slowly: https://github.com/exoscale/puppet/pull/3519

**Comment by irregulator** [comment]
> We actually set `latest` in [common.yaml](https://github.com/exoscale/puppet/blob/6d506e1376a63b049205409bc5d18da9d38ce950/configstore/common.yaml#L33).

you're right, I missed that, thanks ;)

**Pull request merged**
